### ISSUE TITLE
Improve tests to make sure a voucher is executed to complete a withdrawal

### ISSUE THREAD

**Issue by marcelstanley** [cartesi/honeypot#7]
## 📚 Context

Test [*Withdraw request from WITHDRAW_ADDRESS results in a voucher*](https://github.com/cartesi/honeypot/blob/06805147d84f411b5ba545c930afda4f06b9e344/tests/honeypot.test.ts#L67) does not test the full procedure, which could include the execution of the voucher itself.

## ✔️ Solution

Add the following steps to the test:

1. Finish the epoch
2. Execute the voucher
3. Check Bob's balance to make sure the funds were transferred correctly

## 📈 Subtasks

- [ ] [Advance time](https://github.com/cartesi/rollups-examples#advancing-time)
- [ ] Execute the voucher
- [ ] Check Bob's balance

## 🎯 Definition of Done

- [ ] Test passes and Bob's balance matches what is expected
- [ ] All tests pass

**Comment by Abtrade2023** [comment]
Tks you

**Comment by edubart** [comment]
This issue is no longer relevant since development o Honeypot v1 ceased and voucher execution is not within the scope of the new Honeypot v2 test suite (it's tested with the emulator now and detached from the rollups infrastructure).
